### ISSUE TITLE
@par test broken

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#83] opened 2016-03-29 18:22 UTC
@par test is broken. Travis was ignoring it since debug environment variable was not set (fixed now). It is probably coming from the recent changes in ParallelIR.

**Comment by ninegua** [comment] 2016-03-29 18:25
I can confirm it still worked as of commit ea3c30882ee440bcce2be6b4a77d2f578c3eecf7

**Comment by ehsantn** [comment] 2016-03-29 18:49
The problem seems to be that `:n` is not in the escaping variables of the inner lambda. @ninegua could you take a look?

**Comment by ehsantn** [comment] 2016-03-29 20:42
Can't we solve the lack of SSA problem for equivalences for now by being conservative and not establishing correlation when an array has different possible allocation points? Implementation of this seems easy to me in the AST walk code.

A correlation is established only if the sizes are constant integers or assigned once. Therefore, it doesn't matter when the inner lambda is called. Is there a case where the size might be assigned
after inner lambda is called?

The solution for this example seems to me is to merge correlation size variables into inner lambda since they are constants.

**Comment by ninegua** [comment] 2016-03-29 20:50
Why was 6c59cce necessary in the first place? All inner lambdas that should be inlined will be inlined once domain operators are lowered into parfors. We may still have nested parfors, but variables in them are considered to be in the same scope.

**Comment by ehsantn** [comment] 2016-03-29 21:26
The problem is that all optimizations happen before lowering to parfors.

**Comment by ehsantn** [comment] 2016-03-29 21:43
Oh by inner lambda I mean the body of mmap and mmap! nodes. Can they be called somewhere else?

**Comment by ninegua** [comment] 2016-03-29 22:40
The subject is rather delicate. There is at least one known issue #78 with it. Even if we can assume all the safety cautions (constant or assigned once, array object vs. variable, etc.) in place, the fix is not just pulling in the size symbol as an escaping variable because it could clash with a locally defined variable. Probably need to generate a fresh local var to put in the `symbol_array_correlation` array.

Also, you are reusing `domain_lambda` (actually its `linfo`) in the `setEscCorrelations!` function, which is wrong. Because the `linfo` no longer corresponds to the what is in the `ast`, which was created in `lambdaFromDomainLambda`. So it is best to create a new `linfo` from `ast` again before calling `setEscCorrelations!`.

**Comment by ninegua** [comment] 2016-03-30 04:06
In order to get travis back, I pushed a fix f0cd475558257f6ab6914f245a6a2d8d750b7b2b . It throws an error when there is a conflict with local variable names. We'll have to revisit this topic when that happens.

**Closed by ninegua** 2016-03-30 04:06 UTC
