### ISSUE TITLE
Pkg.test("ParallelAccelerator") failing / v0.2.1/ Julia 0.5

### ISSUE THREAD

**Issue by mgr327** [IntelLabs/ParallelAccelerator.jl#127] opened 2016-10-29 22:14 UTC
ParallelAccelerator v0.2.1 test is failing on Julia 0.5 with the message:  
...
Testing miscellaneous features...
/usr/bin/julia: symbol lookup error: /tmp/tmps9k2uN/libcgen_output45.so.1.0: undefined symbol: _Z11cblas_dgemm11CBLAS_ORDER15CBLAS_TRANSPOSES0_iiidPKdiS2_idPdi
...

The full test log  and the Julia versioninfo are below:

`% julia -e 'Pkg.test("ParallelAccelerator")'`
INFO: Computing test dependencies for ParallelAccelerator...
INFO: Installing Cairo v0.2.35
INFO: Installing ColorVectorSpace v0.1.11
INFO: Installing Dates v0.4.4
INFO: Installing FileIO v0.2.0
INFO: Installing Graphics v0.1.3
INFO: Installing ImageMagick v0.1.8
INFO: Installing Images v0.5.14
INFO: Installing IniFile v0.2.5
INFO: Installing SIUnits v0.1.0
INFO: Installing StatsBase v0.11.1
INFO: Installing TexExtensions v0.0.3
INFO: Installing Tk v0.4.0
INFO: Installing Winston v0.12.1
INFO: Installing Zlib v0.1.12
INFO: Building Cairo
INFO: Building ImageMagick
INFO: Building Tk
INFO: Testing ParallelAccelerator
Testing parallel library functions...
WARNING: scale(A::AbstractMatrix,x::AbstractVector) is deprecated, use A \* Diagonal(x) instead.
 in scale(::Array{Float64,2}, ::Array{Float64,1}) at ./deprecated.jl:50
 in ##normalizeW#282(::Array{Float64,2}, ::Int64) at /home/xxxxxx/.julia/v0.5/ParallelAccelerator/test/lib.jl:63
 in test7() at /home/xxxxxx/.julia/v0.5/ParallelAccelerator/test/lib.jl:111
while loading /home/xxxxxx/.julia/v0.5/ParallelAccelerator/test/lib.jl, in expression starting on line 130
Done testing parallel library functions.
Testing parfor support via @par macro...
Done testing parfor.
Testing map and reduce...
Done testing map and reduce.
Testing abs()...
Done testing abs().
Testing constant promotion for pointwise operations...
Done testing constant promotion.
Testing rand()...
Done testing rand()...
Testing BitArrays...
Done testing BitArrays.
Testing ranges...
Done testing ranges.
Testing sequential code...
Done testing sequential code.
Testing cat...
Done testing cat.
Testing hcat...
Done testing hcat.
Testing vcat...
Done testing vcat.
Testing ranges...
Done testing ranges.
Testing miscellaneous features...
/usr/bin/julia: symbol lookup error: /tmp/tmps9k2uN/libcgen_output45.so.1.0: undefined symbol: _Z11cblas_dgemm11CBLAS_ORDER15CBLAS_TRANSPOSES0_iiidPKdiS2_idPdi
=====================================================[ ERROR: ParallelAccelerator ]=====================================================

failed process: Process(`/usr/bin/julia -Cx86-64 -J/usr/lib64/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/xxxxxx/.julia/v0.5/ParallelAccelerator/test/runtests.jl`, ProcessExited(127)) [127]
# 

INFO: Removing Cairo v0.2.35
INFO: Removing ColorVectorSpace v0.1.11
INFO: Removing Dates v0.4.4
INFO: Removing FileIO v0.2.0
INFO: Removing Graphics v0.1.3
INFO: Removing ImageMagick v0.1.8
INFO: Removing Images v0.5.14
INFO: Removing IniFile v0.2.5
INFO: Removing SIUnits v0.1.0
INFO: Removing StatsBase v0.11.1
INFO: Removing TexExtensions v0.0.3
INFO: Removing Tk v0.4.0
INFO: Removing Winston v0.12.1
INFO: Removing Zlib v0.1.12
ERROR: ParallelAccelerator had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258

`% julia -e 'versioninfo()'`
Julia Version 0.5.0
Commit 3c9d753\* (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, westmere)

`% julia -e 'Pkg.status("ParallelAccelerator")'`
- ParallelAccelerator           0.2.1

**Comment by lkuper** [comment] 2016-11-01 21:53
Thanks for the bug report.  It seems like this issue might be specific to OpenBLAS (it's not happening on Travis, where there's no BLAS library, and it's not happening for me (I have MKL)).  Does anyone know what's going on here?

**Comment by lkuper** [comment] 2016-11-01 21:57
Unrelatedly, we probably ought to fix that `scale` deprecation warning.

**Comment by lkuper** [comment] 2017-06-07 01:05
Update (sorry for the long delay): I've done more testing with OpenBLAS and ParallelAccelerator.  I've never been able to reproduce this particular problem.  However, we now know of at least one case where OpenBLAS and ParallelAccelerator do not play nicely together, which may or may not have been the issue here (see #147).  I'm going to close this issue for now, but if you're still having problems under the most recent Julia and ParallelAccelerator releases and the issue is not already covered by bug #147, feel free to reopen this.  Thanks!

**Closed by lkuper** 2017-06-07 01:05 UTC
