### ISSUE TITLE
Compatibility with Julia master branch (0.5)

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/ParallelAccelerator.jl#53] opened 2016-01-23 06:15 UTC
I made a couple fixes, and the only thing that is still broken is wave-2d. This is because in Julia 0.5, the behavior of selection changed. We used to have:

~~~
julia> a=[1 2 3;4 5 6]
a[2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> a[1,1:2]
1x2 Array{Int64,2}:
 1  2
~~~

But now with 0.5, we have:

~~~
julia> a[1,1:2]
2-element Array{Int64,1}:
 1
 2
~~~

So this creates a scenario where the LHS and RHS of `a[1,1:s]=b[1,1:s]` are no longer considered as of the same dimension, because parallel IR is hard coded to treat the LHS as a 2D array (Julia 0.4 behavior), while in Julia 0.5 the LHS is type inferred to be a 1D array.

We need a generic way to handle this kind situation for both 0.4 and 0.5.

**Comment by ninegua** [comment] 2016-01-29 08:04
With the latest [merge of jb/functions branch into master](https://github.com/JuliaLang/julia/commit/9bfd27bd380124174a5f37c342e5c048874d71a4), things changed quite a bit regarding to function and closure representation in ASTs. I'm still digesting the details, but it is safe to say ParallelAccelerator is no longer working with 0.5 until we fix these new incompatibilities.

**Comment by ninegua** [comment] 2016-02-18 00:07
Many of the incompatibilities are fixed in 13f9ac2be3d808f0bcc1f032433219de44d2138e and later commits. However, we are seeing unnecessary `Any` type in the incoming AST, which caused some of the unit tests to fail.

**Comment by ninegua** [comment] 2016-03-25 22:30
As of commit fa7631c5b8e9987eaf1a25feffbdeea372b6b998, among all tests, only the following fails for the latest Julia master branch (0.5):

1. `parfor.jl` Inference issue due to `Box` type being too opaque, which leads to `Any` type being inferred for the return result of function calls on them.
2. `misc.jl` CGen fails at translating `Base.*` and a few other functions because they are not normalized, i.e., function call arguments are Expr instead of variables or constants.
3. `test_lr.jl` CGen cannot handle `Any` type in converting `Base.vect` function to C.

We can't do much about 1 at this moment, but both 2 and 3 are related to CGen unable to re-use some analysis and clean-ups that has been performed in DomainIR. It is perhaps not desirable to run through the entire domain/parallel IR passes for these ASTs being passed directly to CGen. So we'll have to break down Domain IR transformation into two or more smaller passes.

**Comment by ninegua** [comment] 2016-05-17 16:27
We have finally caught up with our previous status after a long over-haul to adapt to the AST changes introduced in the latest Julia 0.5 (master) branch. Travis shows the status for workloads, but not individual tests: https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/130866966

A major roadblock is still about the `Box` type not containing the type of its content. Incoming Julia ASTs often have too many `Any` types, which prevents ParallelAccelerator from successfully translating them.

**Comment by ninegua** [comment] 2016-05-27 18:26
Most recent Julia 0.5 master can use type annotations to get around the `Box` type issue we are having (see [issue 16431](https://github.com/JuliaLang/julia/issues/16431)). In short, here is a BKM to make sure your code continues to work with ParallelAccelerator and Julia 0.5:

1. Give explicit type annotation to all variables that are potentially used within an inner function, this includes parallel comprehensions, `@parfor` macro, and the use of `map` and `reduce` functions. Example: [`test/parfor.jl:54-62`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/test/parfor.jl#L54-L62), [`examples/opt-flow/image.jl:104-105`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/examples/opt-flow/image.jl#L104-L105)

2. It may also be necessary to give the type to the result of a parallel comprehension. Example: [`test/lib.jl:61`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/test/lib.jl#L61), [`examples/k-means/k-means.jl:53-57`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/examples/k-means/k-means.jl#L35-L37), [`examples/opt-flow/image.jl:61-63`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/examples/opt-flow/image.jl#L61-L63)

3. Not directly related to `Box` type, but it is good to not assume implicit conversion between numerical types, and always use explicit conversion. For exmaple `f (x::Int) = x + 0.1` should be written as `f(x::Int) = Float64(x) + 0.1`.

With all recent fixes, the only thing that works (with CGen) in 0.4 but not 0.5 is `wave-2d`, due to the incompatible semantics change to array slices (see first comment in this thread). Most likely we'll have use version check to overcome this problem.

**Comment by ninegua** [comment] 2016-06-02 21:24
By fixing the source code of `wave-2d` to use range `x:x` instead of just `x`, we now have Julia 0.5 working on Travis: https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/134795105. Some more fix is needed for Julia 0.5 on Mac though.

**Comment by ChrisRackauckas** [comment] 2016-08-07 17:52
What's the latest on this?

**Comment by DrTodd13** [comment] 2016-08-07 20:26
With 0.5, we have two backends: the previously existing C backend and the new Julia native threading backend.  The master branch of ParallelAccelerator (and CompilerTools) should now be working with 0.5 with the C backend.  The native threading backend works for all but one of our provided tests (opt-flow) with a single thread.  For multiple threads, we have discovered numerous concurrency issues in Julia itself.  Some of these have been reported to Julia and fixed there but there are other issues that remain.  The threading backend will have experimental status in Julia 0.5 so I don't think they are going to wait for perfection to release 0.5.  We will continue to report these issues we find to Julia and assist with fixes where we can.

**Comment by DrTodd13** [comment] 2016-08-09 20:43
I realize that this is mostly a duplicate of issue95.  We have most things working and if things arise that break 0.5 compatibility we will fix them.

**Closed by DrTodd13** 2016-08-09 20:43 UTC
