### ISSUE TITLE
ParallelAccelerator compilation time

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#12] opened 2015-11-01 14:02 UTC
The first time `ParallelAccelerator` is used, Julia compiles it which takes a long time (~19s on my machine). Most of the time is spent in type inference of ParallelAccelerator. 

The code needs to be refactored for easier type inference. Some variables especially function inputs need to be type annotated. Some functions need to be broken up and refactored to dynamic dispatch format.

**Comment by lkuper** [comment] 2015-12-08 18:49
I'll work with @ehsantn and see if we can get any improvement by refactoring code to use Julia-style dynamic dispatch instead of branching based on types.

**Comment by lkuper** [comment] 2015-12-09 21:08
#28 was a first stab at refactoring a few bits of Parallel IR.  At a first glance, it looks like more progress can be made in CompilerTools.  I'll look there next.

**Comment by lkuper** [comment] 2015-12-16 01:16
Commits https://github.com/IntelLabs/CompilerTools.jl/commit/30ee245423e0740b4eeec609513b1461bece5fad and https://github.com/IntelLabs/CompilerTools.jl/commit/c4e842cebcd4885eb354dcad5cb039be814c44e8 try to do this refactoring in the obvious places in CompilerTools.  In a quick experiment, this seemed to result in a ~0.5s reduction in
compile time for black-scholes (17.63s vs. 18.13s on my desktop machine, averaged over 10 trial runs).

These changes are pretty hairy, and I'm not totally sure if they're semantics-preserving.  But, the tests pass.  If you encounter any new errors and it turns out to be from code I touched, let me know.

At what point should we consider this bug closeable?  I think that the dream of a 9x reduction in compile time is unrealistic.

**Comment by lkuper** [comment] 2015-12-17 22:51
Commits https://github.com/IntelLabs/ParallelAccelerator.jl/commit/26385971fa0a0f0a691f99f11ceb841df049c376 and https://github.com/IntelLabs/ParallelAccelerator.jl/commit/b77ea8a861eaa74328cd0dd62745a4699d35df19 are further progress on this.  On Travis (a 2-core machine with 7.5 GB memory running Ubuntu 14.04), it seems like compile time has improved a fair amount over the last week on our examples.  The listed times for each are in seconds, from a week ago (from [this build](https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/96224624)) and from today [this build](https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/97363897)):

black-scholes:
21.886125777
17.409211793

boltzmann:
26.707941213
20.414715275

gaussian-blur:
23.373856001
18.212819846

harris:
27.789268173
21.157932065

juliaset:
23.450760064
18.145993632

laplace-3d:
22.604418626
17.728987393

opt-flow:
33.627603506
25.554761353

quant:
28.585654887
21.973069792

wave-2d:
20.832001646
16.241740289

I wouldn't put a lot of trust in these results, since each one is only run once, and also, the improvement could be due to other changes made to the compiler during that time.  But it does inspire me to keep chipping away.

**Comment by lkuper** [comment] 2016-01-09 00:41
I just tried comparing compile times for black-scholes as of today with a month ago.  Results for black-scholes as of today (on my 8-core desktop), with Julia 0.5-dev and ParallelAccelerator master@1a4aadf71128a479a1f29e87b2d11027b3ae519d (Wed Jan 6 22:45:36 2016 -0800)

SELFPRIMED 19.888895439
SELFPRIMED 19.758205915
SELFPRIMED 19.588756573
SELFPRIMED 19.825913687
SELFPRIMED 19.755152035

And, with Julia 0.5-dev and ParallelAccelerator master@cd60654ad9b2b9457c50f0c8e31a7a6d2e4376f5 (Tue Dec 8 16:11:57 2015 -0800)

SELFPRIMED 18.91036877
SELFPRIMED 19.102545024
SELFPRIMED 19.231921113
SELFPRIMED 19.076535012
SELFPRIMED 19.180234302

So, if anything, there's been a regression.  :(  On the other hand, plenty of other things have changed about the compiler in the last month that could affect these numbers.  But it is safe to say I'm not seeing any drastic compile time improvements.

@ehsantn It would be good if we could profile again and see how much of compile time is spent in type inference now vs. before.

**Comment by lkuper** [comment] 2016-01-09 00:58
FWIW, here is the same comparison but with Julia 0.4.2, where the numbers are better overall but still a regression between now and a month ago.

current:

SELFPRIMED 18.107248136
SELFPRIMED 18.080389623
SELFPRIMED 18.013348974
SELFPRIMED 17.862677649
SELFPRIMED 17.913133926

December 8:

SELFPRIMED 17.220481111
SELFPRIMED 17.166120496
SELFPRIMED 17.381818736
SELFPRIMED 17.340547496
SELFPRIMED 17.306844817

**Comment by lkuper** [comment] 2016-01-09 01:02
BTW, one of the suggested performance tips for Julia is ["break functions into multiple definitions"](http://docs.julialang.org/en/release-0.4/manual/performance-tips/#break-functions-into-multiple-definitions), which is what we've been doing.  But they also point out that merely adding type annotations does _not_ help (http://docs.julialang.org/en/release-0.4/manual/performance-tips/#type-declarations).  On the other hand, this is about runtime performance, not compile time.

**Comment by ehsantn** [comment] 2016-01-10 01:59
We shouldn't expect improvement until we refactor a significant subtree of the call graph. It will only get worse as we handle more cases and add features.

I will refactor a few functions I've noticed which could help.

**Comment by ehsantn** [comment] 2016-01-13 22:07
I ran Vtune just now on my desktop. The sequence of calls looks complicated but at least 59% of the time is spent in type inference (highlighted line).

![vtune-pa-1-13-2016](https://cloud.githubusercontent.com/assets/2333645/12309272/a8666866-b9fe-11e5-8c99-8ebc9bfebcd9.png)

**Comment by lkuper** [comment] 2016-01-13 23:00
@ehsantn Thank you, that's useful to know!

**Comment by ehsantn** [comment] 2016-01-22 22:45
I added some logging info to low level `typeinf_uncached()` function to see which functions are type inferred repeatedly with the same function signature. The result is attached.

Functions like `translate_call_cartesianarray()` are high on the list maybe because they have `eval()` calls in them. `@code_warntype` shows that a lot of local variables are inferred as `ANY` in the first round.

[sortecount.txt](https://github.com/IntelLabs/ParallelAccelerator.jl/files/101540/sortecount.txt)

**Comment by ninegua** [comment] 2016-01-22 22:49
Somehow can't read your attachment (my browser tab simply crash when I clicked).

Please read my email to you. The reason why some functions are inferred repeatedly was due to recursion. My commit 501379ef43e2a54436c964e256180cd460bb6f0a has already fixed this, including `translate_call_cartesianarray()`.

**Comment by ninegua** [comment] 2016-01-22 23:25
The effect of evals (over GlobalRef) in DomainIR doesn't seem significant when I tried to compare compiling optical flow before and after. But anyway, commit 4ed4981dd556768789981a44ca1b7b39c25d8e4e should have removed all evals from DomainIR.

**Comment by ehsantn** [comment] 2016-01-23 00:21
These guesses all seem to be wrong then. Julia just can't infer a lot of the types easily.

**Comment by lkuper** [comment] 2016-03-15 20:36
With `embed` working again, and with the Julia team promising significant performance improvements in 0.5, we think we can close this for now.

**Closed by lkuper** 2016-03-15 20:36 UTC
Labels: enhancement
